version: '3.8'

services:
  api:
    command: python -m uvicorn app:app --host 0.0.0.0 --port 5000
    image: registry.digitalocean.com/woodward/aliveornot-api:latest
    volumes:
      - ./db.sqlite:/code/db.sqlite
    networks:
      aliveornot:

  caddy:
    image: registry.digitalocean.com/woodward/aliveornot-caddy:latest
    volumes: 
      - ./frontend/public:/usr/share/caddy/
      - ./caddy_data:/data
    ports:
      - 443:8080
      - 80:8081
    env_file:
      - caddy.env.prod
    networks:
      aliveornot:

networks:
  aliveornot:



 