version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    command: python -m uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    image: aliveornot-api
    volumes:
      - ./api:/code
    networks:
      aliveornot:

  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy.dockerfile
    image: aliveornot-caddy
    volumes: 
      - ./frontend/public:/usr/share/caddy/
      - ./caddy_data:/data
    ports:
      - 8080:8080
      - 8081:8081
    env_file:
      - caddy.env.dev
    networks:
      aliveornot:

networks:
  aliveornot:



 