version: '3.8'

services:
  api-dev:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    command: python -m uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    image: aliveornot-api
    volumes:
      - ./api:/code
    networks:
      aliveornot:

  static:
    image: caddy
    volumes: 
      - ./frontend/public:/usr/share/caddy/
      - ./frontend/caddy_data:/data
      - ./docker/files/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:8080
      - 8081:8081
    env_file:
      - caddy.env.dev
    networks:
      aliveornot:

networks:
  aliveornot:



 