---
- name: aliveornot webserver
  hosts: default
  vars:
    users:
    - neal
    - rita
    - alex
  tasks:
    - name: Create user accounts and make them sudo.
      user:
        name: "{{ item }}"  
        shell: /bin/bash
        groups: "sudo"
      with_items: "{{ users }}"
    - name: deploy authorized ssh public keys
    # Just for neal right now as I don't have pubkeys for rita and alex
      authorized_key:
        user: neal
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPb4FdH/vm5+hD0DCt1Bxu1jvjdK/okqRFS/CgQ62790L/CwZOKq599PLPzUPAMCnC1L73kgvggp4uWfLcJoD+LMKJqEkITa9CF0qf/k494gG+LJePAEaRHhKrdisn11NrVBcSOgjJjjlMMa8F2Y7iUqdX3w2cMQuMJOSNdzEZnlDkA906xgVOAHD7nsK/pFh72EhSpx3PTuUlAZaMOKFf3rHzWtuqlmT/o9q/ZRZjSi+jpDZ558+2PdJ81uZzc3q7uKV3wqwqlj6cKI7e/D1ryOxJ4aGjQJPNbVXaIXCa4RnbH7dUhhK0eeHN6niiWoY63JoGRmxImvadcynCN1dWfxcVnhwadAcUh6O6U46XE+9H30hjU2JLAFpORznDOHItaB9BAyKTacog42rgIW6oTRa0lVJcgpV1ca0IhYVMLVQnFMdTxFx6MTUezKbU70cybobLz34piKYN6qnn6NJ6Upfg+mzYb2BJ/LZLcG6OT091izskyP1ydc5dPUK9Ouc= neal@neal-xps
