- name: Installs s3cmd
  apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - python-magic
    - s3cmd

- name: Adds s3 credentials
  template: >
    src=../templates/s3cfg.j2
    dest=~{{ s3cmd_user }}/.s3cfg
    owner={{ s3cmd_user }}
    mode=600
