on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker-compose build api
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker tag aliveornot-api registry.digitalocean.com/woodward/aliveornot-api:${GITHUB_REF##*/}-${git_hash}
          docker tag aliveornot-api registry.digitalocean.com/woodward/aliveornot-api:latest
          docker image ls

      - name: Install doctl                 # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: push image to digitalocean
        run: |
          doctl registry login
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker push registry.digitalocean.com/woodward/aliveornot-api:${GITHUB_REF##*/}-${git_hash}
          docker push registry.digitalocean.com/woodward/aliveornot-api:latest
          old_shas=$(doctl registry repository list-tags  aliveornot-api | grep -E -i -w 'main' | tail -n +3 | awk -F ' ' '{print $8}')
          while IFS= read -r line; 
            prefix="sha:"
            sha=${line#"$prefix"}
            echo "deleting image manifest with sha $sha"
            doct registry repository delete-tag aliveornot-api $sha
          done <<< "$old_shas"
          

