on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker-compose build
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker tag aliveornot-api registry.digitalocean.com/woodward/aliveornot-api:${GITHUB_REF##*/}-${git_hash}
          docker tag aliveornot-caddy registry.digitalocean.com/woodward/aliveornot-caddy:${GITHUB_REF##*/}-${git_hash}
          docker tag aliveornot-api registry.digitalocean.com/woodward/aliveornot-api:latest
          docker tag aliveornot-caddy registry.digitalocean.com/woodward/aliveornot-caddy:latest
          docker image ls

      - name: Install doctl                 # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: push image to digitalocean
        run: |
          doctl registry login
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker push registry.digitalocean.com/woodward/aliveornot-api:${GITHUB_REF##*/}-${git_hash}
          docker push registry.digitalocean.com/woodward/aliveornot-api:latest
          old_shas=$(doctl registry repository list-tags  aliveornot-api | grep -E -i -w 'main' | tail -n +3 | awk -F ' ' '{print $8}')
          if [[ $old_shas ]]; then
            while IFS= read -r line; 
            do
              echo "deleting image manifest with sha $line"
              doctl registry repository delete-manifest aliveornot-caddy $line --force
            done <<< "$old_shas"
          fi
          while IFS= read -r line; 
          do
            echo "deleting image manifest with sha $line"
            doctl registry repository delete-manifest aliveornot-api $line --force
          done <<< "$old_shas"

          docker push registry.digitalocean.com/woodward/aliveornot-caddy:${GITHUB_REF##*/}-${git_hash}
          docker push registry.digitalocean.com/woodward/aliveornot-caddy:latest
          old_shas=$(doctl registry repository list-tags  aliveornot-caddy | grep -E -i -w 'main' | tail -n +3 | awk -F ' ' '{print $8}')
          if [[ $old_shas ]]; then
            while IFS= read -r line; 
            do
              echo "deleting image manifest with sha $line"
              doctl registry repository delete-manifest aliveornot-caddy $line --force
            done <<< "$old_shas"
          fi
          doctl registry logout
