on:
  [push, pull_request]

jobs:
  plan:
    if: ( github.event_name == 'pull_request' || contains(github.event.head_commit.message, 'tf plan') )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          terraform:
            - 'terraform/**'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.2

    # run only if 'backend' files were changed
    - name: terraform plan
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      if: steps.filter.outputs.terraform == 'true'
      run: |
        cd terraform && terraform init;
        terraform plan -out plan.tfplan;
    - name: terraform apply
      if: steps.filter.outputs.terraform == 'true' && github.ref == 'refs/heads/main'
      run: terraform plan --auto-approve plan.tfplan
