on:
  push:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          terraform:
            - 'terraform/**'

    # run only if 'backend' files were changed
    - name: backend tests
      if: steps.filter.outputs.terraform == 'true' && contains(github.event.head_commit.message, 'tf plan')
      run: "echo i'm in the action"
