on:
  push:

jobs:
  plan:
    if: contains(github.event.head_commit.message, 'tf plan')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          terraform:
            - 'terraform/**'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # run only if 'backend' files were changed
    - name: backend tests
      if: steps.filter.outputs.terraform == 'true'
      run: "ls"
